#!/bin/bash
sudo chage -m 2 root
sudo chage -m 2 daemon
sudo chage -m 2 bin
sudo chage -m 2 sys
sudo chage -m 2 sync
sudo chage -m 2 games
sudo chage -m 2 man
sudo chage -m 2 lp
sudo chage -m 2 mail
sudo chage -m 2 news
sudo chage -m 2 uucp
sudo chage -m 2 proxy
sudo chage -m 2 www-data
sudo chage -m 2 backup
sudo chage -m 2 list
sudo chage -m 2 irc
sudo chage -m 2 gnats
sudo chage -m 2 nobody
sudo chage -m 2 _apt
sudo chage -m 2 systemd-network
sudo chage -m 2 systemd-resolve
sudo chage -m 2 eguelin
sudo chage -m 2 systemd-timesync
sudo chage -m 2 systemd-coredump
sudo chage -m 2 messagebus
sudo chage -m 2 sshd

sudo chage -M 30 root
sudo chage -M 30 daemon
sudo chage -M 30 bin
sudo chage -M 30 sys
sudo chage -M 30 sync
sudo chage -M 30 games
sudo chage -M 30 man
sudo chage -M 30 lp
sudo chage -M 30 mail
sudo chage -M 30 news
sudo chage -M 30 uucp
sudo chage -M 30 proxy
sudo chage -M 30 www-data
sudo chage -M 30 backup
sudo chage -M 30 list
sudo chage -M 30 irc
sudo chage -M 30 gnats
sudo chage -M 30 nobody
sudo chage -M 30 _apt
sudo chage -M 30 systemd-network
sudo chage -M 30 systemd-resolve
sudo chage -M 30 eguelin
sudo chage -M 30 systemd-timesync
sudo chage -M 30 systemd-coredump
sudo chage -M 30 messagebus
sudo chage -M 30 sshd

sudo chage -m 0 root
sudo chage -m 0 daemon
sudo chage -m 0 bin
sudo chage -m 0 sys
sudo chage -m 0 sync
sudo chage -m 0 games
sudo chage -m 0 man
sudo chage -m 0 lp
sudo chage -m 0 mail
sudo chage -m 0 news
sudo chage -m 0 uucp
sudo chage -m 0 proxy
sudo chage -m 0 www-data
sudo chage -m 0 backup
sudo chage -m 0 list
sudo chage -m 0 irc
sudo chage -m 0 gnats
sudo chage -m 0 nobody
sudo chage -m 0 _apt
sudo chage -m 0 systemd-network
sudo chage -m 0 systemd-resolve
sudo chage -m 0 eguelin
sudo chage -m 0 systemd-timesync
sudo chage -m 0 systemd-coredump
sudo chage -m 0 messagebus
sudo chage -m 0 sshd

sudo chage -M 99999 root
sudo chage -M 99999 daemon
sudo chage -M 99999 bin
sudo chage -M 99999 sys
sudo chage -M 99999 sync
sudo chage -M 99999 games
sudo chage -M 99999 man
sudo chage -M 99999 lp
sudo chage -M 99999 mail
sudo chage -M 99999 news
sudo chage -M 99999 uucp
sudo chage -M 99999 proxy
sudo chage -M 99999 www-data
sudo chage -M 99999 backup
sudo chage -M 99999 list
sudo chage -M 99999 irc
sudo chage -M 99999 gnats
sudo chage -M 99999 nobody
sudo chage -M 99999 _apt
sudo chage -M 99999 systemd-network
sudo chage -M 99999 systemd-resolve
sudo chage -M 99999 eguelin
sudo chage -M 99999 systemd-timesync
sudo chage -M 99999 systemd-coredump
sudo chage -M 99999 messagebus
sudo chage -M 99999 sshd
